#!/usr/bin/python3
import argparse
import os
import subprocess

from utils import *


def stop_job(args):
    os.execl('/usr/bin/scancel',
             '/usr/bin/scancel', args.jobid)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        prog='astop',
        description='Stop (kill) a running job.',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        'jobid',
        help='JobID of the job to be stopped.'
    )

    args = parser.parse_args()
    stop_job(args)
